### PR TITLE
Arrays-Day1-Easy

### PR DESCRIPTION
**Pull request by vaibhav721**

### CODE REVIEW

**Comment by InclinedScorpio** [comment]
@vaibhav721  Create a different branch, don't use master, otherwise you won't be able to keep track of your questions :)

To create another branch
- git checkout -b <branch_name>
- git push <branch_name>

**Comment by InclinedScorpio** [comment]
@vaibhav721  Can you include question url on top of questions so I can also refer? :)

**Comment by vaibhav721** [comment]
I need to merge from my branch to inclinedScorpio master branch right?

**Comment by InclinedScorpio** [comment]
> I need to merge from my branch to inclinedScorpio master branch right?

In vaibhav-questions (I have created the branch now)

**Pull request closed without merging**
